tar -xvf packet.tar;
mv ./code/db_init ./;
mv ./code/pp ./;
sh db_init;
clang -c code/sqlite3.c;
cp sqlite3.o code/;
clang -static code/shell.c code/sqlite3.o -lpthread -o ./sqlite3;
clang -static code/upload.c code/sqlite3.o -lpthread -o ./upld;
clang -static code/rem.c code/sqlite3.o -lpthread -o ./remove;
clang -static code/file.c code/sqlite3.o -lpthread -o ./file;
clang -static code/view.c code/sqlite3.o -lpthread -o ./vew;
clang -static code/chkses.c code/sqlite3.o -lpthread -o ./chk;
clang -static code/auth.c code/sqlite3.o -lpthread -o ./auth;
clang -static code/uuidgen.c code/sqlite3.o -lpthread -o ./uuidgen;
mv ./upld /var/www/cgi-bin/;
mv ./remove /var/www/cgi-bin/;
mv ./file /var/www/cgi-bin/;
mv ./vew /var/www/cgi-bin/;
mv ./chk /var/www/cgi-bin/;
mv ./auth /var/www/cgi-bin/;
mv ./uuidgen /var/www/cgi-bin/;
mv ./code/rem /var/www/cgi-bin/;
mv ./code/upload /var/www/cgi-bin/;
mv ./code/view /var/www/cgi-bin/;
mv ./code/userdb /var/www/cgi-bin/db;
mv ./sqlite3 /var/www/cgi-bin/;
chmod -R a+rwx /var/www/cgi-bin;
cat frontend/js/util.js >> conf.cfg;
mv conf.cfg frontend/js/util.js;
mv ./frontend/* /var/www/htdocs/;
cp -r usrbin/usr/* /var/www/usr;
cp -r usrbin/bin/* /var/www/bin;
rcctl restart httpd;
tar -cvf /root/build.tar /var/www;
cp httpd.conf /etc/;
tar -f /root/build.tar -r httpd.conf;
tar -cvf /root/upload.tar /root/build.tar;
tar -f /root/upload.tar -r cms_builder;
tar -cvf /root/build2.tar view;
tar -cvf /root/view.tar /root/build2.tar;
tar -f /root/view.tar -r view_builder;
