make:
	clang -static upload.c sqlite3.o -lpthread -o upld
	clang -static rem.c sqlite3.o -lpthread -o remove
	clang -static file.c sqlite3.o -lpthread -o file
	clang -static view.c sqlite3.o -lpthread -o vew
	clang -static chkses.c sqlite3.o -lpthread -o chk

